// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp6SSGFp1sAZX0K05sONAE_fP1NRxaJIg',
    appId: '1:968262168119:web:39b4d28c9ae91c39f619b2',
    messagingSenderId: '968262168119',
    projectId: 'cartech5',
    authDomain: 'cartech5.firebaseapp.com',
    storageBucket: 'cartech5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD00bc_c8JlaLhlXjOaThADFHOrxuGVOQs',
    appId: '1:968262168119:android:74d3404998c1ab20f619b2',
    messagingSenderId: '968262168119',
    projectId: 'cartech5',
    storageBucket: 'cartech5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDSAY9eSNG9xtZuCbKH-Scn250XoLDHSY',
    appId: '1:968262168119:ios:6c7b74396d3f7d5af619b2',
    messagingSenderId: '968262168119',
    projectId: 'cartech5',
    storageBucket: 'cartech5.appspot.com',
    iosBundleId: 'com.example.carcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp6SSGFp1sAZX0K05sONAE_fP1NRxaJIg',
    appId: '1:968262168119:web:2891bd5b30965a27f619b2',
    messagingSenderId: '968262168119',
    projectId: 'cartech5',
    authDomain: 'cartech5.firebaseapp.com',
    storageBucket: 'cartech5.appspot.com',
  );
}
