// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBadXxssbiyfbeVt9tYpwDWf0PD-Vl9dqU',
    appId: '1:805671777132:web:adae34c0ea0e9a030eb949',
    messagingSenderId: '805671777132',
    projectId: 'kurs11',
    authDomain: 'kurs11.firebaseapp.com',
    storageBucket: 'kurs11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeyNfjpu7-FxzC9S_lSkMG7lkvQhoSKQo',
    appId: '1:805671777132:android:f9e115060751435f0eb949',
    messagingSenderId: '805671777132',
    projectId: 'kurs11',
    storageBucket: 'kurs11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByBSSQpTRHuPtSs72F2yimKlOGR2WuEPE',
    appId: '1:805671777132:ios:25b72fe2bfc988910eb949',
    messagingSenderId: '805671777132',
    projectId: 'kurs11',
    storageBucket: 'kurs11.appspot.com',
    iosBundleId: 'com.example.gleb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByBSSQpTRHuPtSs72F2yimKlOGR2WuEPE',
    appId: '1:805671777132:ios:25b72fe2bfc988910eb949',
    messagingSenderId: '805671777132',
    projectId: 'kurs11',
    storageBucket: 'kurs11.appspot.com',
    iosBundleId: 'com.example.gleb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBadXxssbiyfbeVt9tYpwDWf0PD-Vl9dqU',
    appId: '1:805671777132:web:bd575b595edbccb20eb949',
    messagingSenderId: '805671777132',
    projectId: 'kurs11',
    authDomain: 'kurs11.firebaseapp.com',
    storageBucket: 'kurs11.appspot.com',
  );
}
